learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

#TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns = [
    path('other/',views.other,name='other'),
    path('relative/',views.relative,name='relative'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text':"hello World",'Number':"100"}
    return render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html') 

def relative(request):
    return render(request,'basic_app/relative_url_template.html')       

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base File</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Brand</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index'%}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'basic_app:other'%}">Other</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'basic_app:relative'%}">Relative</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index'%}">Admin</a>
              </li>
        </ul>
    </div>
</nav>
<br><br><br>

<div class="container">
{% block body_block %}
<!-- ANYTHING OUTSIDE THIS WILL BE INHARITED IF YOU EXTENDS THIS  -->
{% endblock %}
</div>
</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>

{%extends 'basic_app/base.html'%}
{% load myextras %}
{% block body_block%}
<H1>WELCOME TO INDEX PAGE!</H1>
<h2>Go to the /basic_app/relative to see the other page</h2>
<h1>{{text|cut:'hello'}}</h1>
<h1>{{Number|add:'99'}}</h1>
{% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html'%}
{%block body_block%}
<H1>WELCOME TO OTHER!</H1>
<h2>This is the example of template inharitance</h2>
{% endblock %}

learning_templates/templates/basic_app/relative_url_template.html
<!DOCTYPE html>
{%extends 'basic_app/base.html'%}

{%block body_block%}
    <h1>WELCOME TO RELATIVE URL TEMPLATE</h1>
    <a href="{% url 'basic_app:other'%}">LINK FOR THE OTHER PAGE USING RELATIVE URL</a>
    <br><br><br>
    <a href="{% url 'admin:index'%}">LINK FOR THE ADMIN PAGE</a><br><br><br>
    <a href="{%url 'index'%}">LINK FOR THE INDEX PAGE</a><br><br>
{%endblock%}